### ISSUE TITLE
[Illustration Request] Blog Post Illustration Request - MongoDB

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/marketing#27]
**Objectives**: Create a custom graphic for the MongoDB Blog Post
**Assignees**: @rochelledai @lillyp3 
**Deadline**: 4/14/20

### Detailed Notes
Create an illustraton to accompany a blogpost about us collaborating with MongoDB to help students learn about industry standard testing protocols.

**Comment by rochelledai** [comment]
Total duration of project: 1 week

Our process/timeline:

**0. Receive Project Brief**  _4/10, Friday_

_What does the client need?_
A graphic showing:
- students/people collaborating and working together to "build"
- a database (MongoDB)
- code

_Who is the target audience?_
The graphic will be used in case studies targeted towards professors and blog posts targeted towards college students. 

**1. Brainstorm/ Sketches** _4/11-12, Sat-Sun_

Lilly and I send sketches back and forth, provide feedback and work together to land on one cohesive idea/sketch. Total sketches: 17
I provide reference images of concepts and graphic qualities like color scheme or art style.
Final Sketch: 
![finalsketch](https://user-images.githubusercontent.com/63178891/79544487-f3d1d280-8043-11ea-9311-cb626bf86cd6.jpg)

**2. First Iteration** _4/13-15, Mon-Wed_
Lilly uses adobe illustrator to digitize the sketch. We meet over zoom and work on building the initial graphic.
First iteration:
![firstit](https://user-images.githubusercontent.com/63178891/79546743-c6872380-8047-11ea-8cdf-cbe9ca58ba89.png)
I provide feedback:
![feedbackall](https://user-images.githubusercontent.com/63178891/79546847-f504fe80-8047-11ea-80d3-04834d6dc898.jpg)
- add more visual energy by thinking about diagonal paths or triangle shapes that are being created (see annotation)

- Redraw people; play with more uneven proportions and shapes, size, to create more white space to make their posture and body language more clear. (ref provided.) make sure that it is clear that the middle person is handing off the code panel to the person above.

- fix 3D block perspective and make sure everything is aligned accurately

- change the light so that it is concentrated in the center of the blocks rather than the perimeter. this will also provide more room for the people to sit and stand.

- make the top face of the 3D blocks the lightest shade of blue, then the rest of the faces darker (opposite of current treatment)

- add pie charts, bar graphs, code, etc to code panels. 

- stick to a cleaner color palette for a more professional look; provided ref imgs of graphics and how color is used. noted that there is normally 1 or 2 bright, accent colors and analogous/muted neutral colors. 

**3. Second Iteration** _4/15-16, Wed-Thurs_
Lilly incorporates the feedback:
![second it](https://user-images.githubusercontent.com/63178891/79547855-62fdf580-8049-11ea-8551-29bb205f4e33.png)
I offer more feedback:

- The colors and people look much better

- move and redraw the light so that it is in front rather than in the back. the middle light should be behind the top block

- color of code panels need to change do that they dont blend in so much

- experiment with moving position of people

Lilly makes edits:
![seconditb](https://user-images.githubusercontent.com/63178891/79548874-f7b52300-804a-11ea-9085-414aba8c7a0a.png)

I go in and start working/making edits to the illustrator file:
![mongomock_4 16_1am](https://user-images.githubusercontent.com/63178891/79549095-5b3f5080-804b-11ea-920d-a3b1114fc3b3.jpg)
- changed the color of the code panels

- add details to code panels

- move 3d block objects and people

- made a 1 level version of graphic 

I request Lilly to redraw the second girl on the middle block. Lilly creates different versions of the graphic- 2 level, 1 level

**4. Finalizing Graphic** _4/16-17, Thurs-Fri_
Request Lilly to clean up the illustrator file (deleting unused layers and objects, organizing artboards etc) and creating squares containing the colors used in the graphic. Lilly exports as svg and png, uploads to bit project 2020 drive. 
I edit the illustrator file to organize objects, group items together for easier future work (moving and recoloring objects etc)

FINAL GRAPHIC:
![finalmongodb](https://user-images.githubusercontent.com/63178891/79550241-ec62f700-804c-11ea-8946-c30fd7bec012.png)
