### ISSUE TITLE
Postman Graphic

### ISSUE THREAD

**Issue by rochelledai** [bitprj/marketing#48]
**Objectives**: Create a graphic combining Covid 19 with Postman API. 
**Assignees**: @lillyp3 @adrienne-lee @rochelledai 
**Deadline**: **Saturday, 4/25/20**

### Detailed Notes
**0. Project brief**
Create an illustration to accompany a blogpost about "Students (who have no exp in computer science) using big data to do research projects in the social sciences".

**WHAT is the graphic about?** 
Students used the Twitter API to analyze and gain insights with location based Covid-19 data. Bit Project hosted a computational social science boot camp targeted towards communication majors to teach them code and how to use the Twitter API to perform sentiment analysis and data visualization. 

**WHO is the graphic for?**
The graphics will be used in case studies targeted towards professors and blog posts targeted towards college students.

**Comment by rochelledai** [comment]
**1. Brainstorm/Sketches** _4/16-17, Thurs-Fri_
Twitter API is used to compute and analyze large amounts of data to see hidden connections and correlations in human behavior/society. 

We need a graphic showing:
- Students collaborating *need to show that students have no background in CS.

- Coding/ big data

- sense of location/real world application 

Lilly and I share sketches back and forth to determine a concept. Shared reference imgs as well.
Total Sketches (Lilly and Rochelle): 15

Final sketch:
![image](https://user-images.githubusercontent.com/63178891/79670003-95584180-8174-11ea-9adf-781a75b2b381.png)

We determined that the necessary assets for this graphic are:

- people

- code panels

- globe

- 3D blocks

**Comment by rochelledai** [comment]
**2. First Iteration(s)** _4/17-18, Fri-Sat_
Lilly creates a rough mockup in Illustrator:
![firstiter](https://user-images.githubusercontent.com/63178891/79670131-ace3fa00-8175-11ea-9a3e-85254cfd5f86.png)
I provide feedback:
- Needs more **Hierarchy**. What should the viewers see first, second, and last? What is the most important part of the graphic? We need to use **color, scale, and positioning to create a clear hierarchy** (see points below)

- **Color:** An accent color should be used on the globe while everything else is more neutral. Be concise with colors to make things cleaner and easy to understand

- **Scale:** The globe should be larger than the blocks/people. The people should be the smallest elements, blocks are medium, then globe is the largest. 

- **Positioning:** There needs to be more **contrast** in the heights of the 3dblocks so that it is very clear which blocks/levels are taller than others (very high vs. very low juxtaposition).   

- Make the group of 3 people on the left block facing each other, as if working in a group.

- Add more white space around the globe so that things are less cramped and more spaced out.

- the lights should be more concentrated/smaller instead of filling the blocks all the way to the perimeter

- position the blocks to create a triangle formation 

Lilly incorporates the feedback:
![good](https://user-images.githubusercontent.com/63178891/79671185-54b0f600-817d-11ea-97a8-d50e36b03a9f.jpg)

I provide more feedback:
![image](https://user-images.githubusercontent.com/63178891/79670522-98edc780-8178-11ea-9049-94174767669b.png)

- make it clear that the blocks are at different levels, similar to stepping stones (see annotation)

- Right img is example of good spacing: The spacing between top block and globe (yellow highlight) should be tighter than the spacing between the front/left block and globe (purple). The more contrast in spacing helps add depth. 

- The block in the very back should be smaller than the block in the front/left to help show that it is farther away/behind the globe. Possibly consider using various capacities to communicate depth.

- consider using a different kind of light/texture on the globe to help differentiate it from the blocks. 

- clean up the colors-- the blocks blend in too much, making the graphic overall feel muddy? consider changing the color of blocks. This issue can be revisited near the end as well. 

- redraw/ create more people assets in various poses that show the "no background in CS" element. ex. a girl in front of podium while behind is code panel? 

Assigned @adrienne-lee to explore different treatments with various positioning and shapes either through sketches or on illustrator.

**Comment by lillyp3** [comment]
**3. Second iterations** _4/19-21, Sun-Tues_
Adrienne provides feedback and sketches to revise our first iteration
![IMG_1737](https://user-images.githubusercontent.com/63167588/80660024-6b89ff00-8a3f-11ea-9720-aa665cfad9e2.jpg)
![IMG_1738](https://user-images.githubusercontent.com/63167588/80660035-717fe000-8a3f-11ea-838b-822fd72b8b98.JPG)

She suggests new positions for the 3D blocks and people

In illustrator I take her ideas and create mockups while experimenting with different colors
![04_19_Mockup2](https://user-images.githubusercontent.com/63167588/80660162-c4599780-8a3f-11ea-80e0-c9c1c4f56b78.png)
![04_19_Mockup1](https://user-images.githubusercontent.com/63167588/80660166-c6bbf180-8a3f-11ea-992c-d5176f633d27.png)

We decide to move forward with the idea of having the blocks curve around the globe and descend in height.

Adrienne works on a new color scheme incorporating shades of orange that go with the Postman brand:

![Bit_TwitterAPI_CASEStudy-02](https://user-images.githubusercontent.com/63167588/80660420-7d1fd680-8a40-11ea-8678-ffc8a4d82ec2.png)

**4. Third iterations,** _4/22-23 Wed-Thurs_

Rochelle and I discuss the idea of incorporating small, blocks to represent the colored blocks used in the bitblox game from the Postman API workshop. The game featured four teams: blue, yellow, red, and green.

I create mockups with our new idea:
![Bit_TwitterAPI_CASEStudy_04-22Mock1](https://user-images.githubusercontent.com/63167588/80660732-64fc8700-8a41-11ea-8351-58705db7e10d.png)
![Bit_TwitterAPI_CASEStudy_04-22_Mock3](https://user-images.githubusercontent.com/63167588/80660760-72b20c80-8a41-11ea-9222-53ee71c21fa5.png)

Rochelle provides feedback:
- eliminate lights under large 3D blocks
- simplify to 3 main 3D blocks
- have fewer colored blocks because it looks too busy
- incorporate a large code panel at the back that will curve around the globe
- add details to the globe
![lillyidea](https://user-images.githubusercontent.com/63167588/80660883-dd634800-8a41-11ea-8b84-a4cdf82f61b5.jpg)

Taking that feedback I produce a mock up:
![Bit_TwitterAPI_CASEStudy_4-23_MockUp](https://user-images.githubusercontent.com/63167588/80660950-1dc2c600-8a42-11ea-8496-daaf3167a6f2.png)

- I added details to the globe and code panels
- the small graphics of viruses and the various graphs such as flattening the curve and the increasing line graph show the use of COVID-19 data

5. Final iteration, 4/24 - Fri

Rochelle edits my mockup: 

![postman mock](https://user-images.githubusercontent.com/63167588/80661320-2f589d80-8a43-11ea-9c20-a83f5ab2e4bc.jpg)

- more specific COVID-19 data

- changes blue code panels to all pink/orange gradient

- changes the small blocks from the colors of the bitblox game to an orange shade that matches the code panels

- changes the details on the globe to create more recognizable land features

- eliminates the light from underneath and around the globe
